version: "3.8"

services:

  app:
    build: .docker
    volumes:
      - ./:/var/www
      - .docker/php/conf.ini:/usr/local/etc/php/conf.d/conf.ini
    working_dir: /var/www
    networks:
      - network_database_mysql

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    networks:
      - network_database_mysql
    ports:
      - 80:80
    depends_on:
      - app

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - network_database_mysql

networks:
  network_database_mysql:
    external:
      name: mysql_database
